version: 2.3

jobs:
  data_processing:
    docker:
      - image: cimg/python:3.9  # Python 3.9 image
    steps:
      - checkout:
          path: ~/project
          ref: main  # Replace 'main' with your branch name or commit hash

      - run:
          name: Set up environment
          command: |
            python -m pip install --upgrade pip
            pip install notebook pandas matplotlib seaborn  # Example dependencies

      # Create necessary directories
      - run:
          name: Create directories
          command: mkdir -p ~/project/notebooks/processed_notebooks

      # Run Jupyter notebook conversion
      - run:
          name: Execute data cleaning notebook
          command: |
            jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute ~/project/notebooks/data-preprocessing.ipynb --output ~/project/notebooks/processed_notebooks/data-preprocessing.ipynb
          working_directory: ~/project

workflows:
  version: 2
  build_and_test:
    jobs:
      - data_processing
